name: Build & Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Retrieve Public IP of EC2 instance
        id: ec2
        run: |
          INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids 'i-0c3a87c07b715a42f' --query "Reservations[].Instances[].PublicIpAddress" --output text)
          echo "::set-output name=instance_ip::$INSTANCE_PUBLIC_IP"
      - name: Deploy to EC2 instances
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_AWS_KCYUAN_EC2_SG_1 }}
            SSH_USER: "ec2-user"
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${SSH_USER}@${{ steps.ec2.outputs.instance_ip }} -vv '
          ls -al
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          docker login --username kcyuan --password dckr_pat_7kcQijMNZ7k72zcH4KtMV5MdfPM
          docker pull kcyuan/ai-animated-images
          docker run -d -p 8080:8080 -p 8081:8081 --name ai-animated-images kcyuan/ai-animated-images:latest
          '